
---
title: "Activist Thought Ground"
description: "Reflections on animal ethics, structural violence, and moral disobedience"
baseurl: "/wa-animal-welfare-transparency/philosophy"
url: "https://helloluna.github.io"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme

# Optional aesthetics
minimal_mistakes_skin: "default"
markdown: kramdown
kramdown:
  input: GFM

# Collections
collections:
  chapters:
    output: true
    permalink: /:collection/:name/

# Navigation
include:
  - _pages
  - _chapters

defaults:
  - scope:
      path: "_chapters"
      type: chapters
    values:
      layout: single
      author_profile: false
      read_time: true
      toc: true
      toc_sticky: true
      comments: false
